### ISSUE TITLE
error on push file

### ISSUE THREAD

**Issue by jonpolak** [GustavoKatel/pushbullet-cli#33]
```
jojo-> pb version
PushBullet CLI, version 0.7.5

jojo-> pb push --file ~/.ssh/id_rsa.pub 
Traceback (most recent call last):
  File "/home/jojo/sources/pb/bin/pb", line 11, in <module>
    sys.exit(main())
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/pushbullet_cli/app.py", line 166, in push
    _push(**kwargs)
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/pushbullet_cli/app.py", line 56, in _push
    file_data = pb.upload_file(f, os.path.basename(file_path))
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/pushbullet/pushbullet.py", line 203, in upload_file
    file_type = get_file_type(f, file_name)
  File "/home/jojo/sources/pb/lib/python3.5/site-packages/pushbullet/filetype.py", line 4, in _magic_get_file_type
    return file_type.decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'

```

I saw your response to a similar error was commit [517e092](https://github.com/r-darwish/pushbullet-cli/commit/517e092c04bc70782ac1b415efe09b133bd6aa16) - that was back in version 0.6

**Comment by GustavoKatel** [comment]
Hi! Which python version are you using?

**Comment by jonpolak** [comment]
python 2.7.12  / python 3.5.2

**Comment by GustavoKatel** [comment]
Hi! I've managed to reproduce it. The problem is with the pushbullet api library. This PR (https://github.com/randomchars/pushbullet.py/pull/111) that I've made will fix the underlying problem. I will update as soon as they approve the PR. I will also let this open until then.

**Comment by GustavoKatel** [comment]
Fixed. Sorry for the long delay
