### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qwIvan** [GustavoKatel/pushbullet-cli#40]
Traceback (most recent call last):
  File "/usr/bin/pb", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-magic' distribution was not found and is required by pushbullet.py

I am already installed 'python-magic'

**Comment by GustavoKatel** [comment]
Did you install it via pip? Can you describe the steps to reproduce the error?

**Comment by GustavoKatel** [comment]
This error is related to the python-magic installation and not directly related to pushbullet-ci.

I recommend you trying to install `python-magic` and/or `python-magic-bi`. Please feel free to reopen, if you think necessary.

Thanks
