### ISSUE TITLE
i'm also getting same error . when i'm trying to execute the code then it shows the same issue . please give me some advise how can i come out from this error.

### ISSUE THREAD

**Issue by priyanshgupta1998** [GustavoKatel/pushbullet-cli#57]
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "/usr/local/bin/pb", line 9, in <module>
    load_entry_point('Pushbullet-CLI==0.1', 'console_scripts', 'pb')()
  File "/usr/local/lib/python2.7/dist-packages/Pushbullet_CLI-0.1-py2.7.egg/pushbullet_cli/app.py", line 111, in main
    pb = PushBullet(api_key)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 29, in **init**
    self.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 267, in refresh
    self._load_devices()
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 42, in _load_devices
    resp_dict = self._get_data(self.DEVICES_URL)
  File "/usr/local/lib/python2.7/dist-packages/pushbullet.py-0.8.1-py2.7.egg/pushbullet/pushbullet.py", line 35, in _get_data
    raise InvalidKeyError()
pushbullet.errors.InvalidKeyError

_Originally posted by @andyforceno in https://github.com/GustavoKatel/pushbullet-cli/issues/14#issuecomment-100087144_

**Comment by andyforceno** [comment]
This happened to me a few years ago, there might be a better way to go about this. Looking back on the comment you referenced, it looks like I fixed it by making the changes from this commit [27ee63bf8162b0a458fbda4b2f554446406465f1](https://github.com/GustavoKatel/pushbullet-cli/commit/27ee63bf8162b0a458fbda4b2f554446406465f1) to the file `app.py` in the pushbullet-cli source. I would think that change has been made in any of the [releases](https://github.com/GustavoKatel/pushbullet-cli/releases) since 2015, though.

**Comment by GustavoKatel** [comment]
Thanks for answering this @andyforceno 

@priyanshgupta1998 You're using a pretty old version `Pushbullet-CLI==0.1` from 2015. Could you try upgrading to the latest PyPI version?

I will close this and feel free to re-open if the error persists.
